/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KeypressRouteImport } from './routes/keypress'

const KeypressRoute = KeypressRouteImport.update({
  id: '/keypress',
  path: '/keypress',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/keypress': typeof KeypressRoute
}
export interface FileRoutesByTo {
  '/keypress': typeof KeypressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/keypress': typeof KeypressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/keypress'
  fileRoutesByTo: FileRoutesByTo
  to: '/keypress'
  id: '__root__' | '/keypress'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  KeypressRoute: typeof KeypressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/keypress': {
      id: '/keypress'
      path: '/keypress'
      fullPath: '/keypress'
      preLoaderRoute: typeof KeypressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  KeypressRoute: KeypressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
